SELECT INV.FICHENO, INV.DATE_,CLC.CODE,CLC.DEFINITION_, ITM.CODE,ITM.NAME  FROM LG_001_01_INVOICE INV , LG_001_CLCARD CLC ,
LG_001_01_STLINE STL ,
LG_001_ITEMS ITM WHERE INV.CLIENTREF=CLC.LOGICALREF AND STL.STOCKREF=ITM.LOGICALREF AND STL.INVOICEREF=INV.LOGICALREF
